server:
  port: 8081
logging:
  file:
    name: logstash/pipeline/movies.log
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: movie
  jackson:
    default-property-inclusion: NON_NULL
  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_HOST}:5432/postgres
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
  elasticsearch:
    rest:
      uris: ${ELASTIC_SERVER}:9200
services:
  review-url: ${REVIEW_URL}
kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}:9092