server:
  port: 8081

spring:
  application:
    name: movie
  jackson:
    default-property-inclusion: NON_NULL
  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_HOST}:5432/movie
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always

#eureka:
#  client:
#    service-url:
#      default-zone: http://${EUREKA_HOST}:8761/eureka

services:
  review-url: ${REVIEW_URL}

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}:9092