server:
  port: 8081

spring:
  config:
    import: .env[.properties]
  application:
    name: movie
  jackson:
    default-property-inclusion: NON_NULL
  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_HOST}:5432/movie
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOST}

services:
  review-url: ${REVIEW_URL}
  
kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}