scrape_configs:
  - job_name: "Movie app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: "Prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]